### ISSUE TITLE
Syntax error in __init__ file

### ISSUE THREAD

**Issue by nickchak21** [brandones/graphpca#2]
When I use the package, doing `import graphpca` causes an error.

The error stack trace is below:
`Traceback (most recent call last):
  File "/Users/nickchak/Documents/polarizationlab/tw/adjacency_matrix_creator.py", line 4, in <module>
    import graphpca
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/graphpca/__init__.py", line 282
    except ArpackNoConvergence, e:
                              ^
SyntaxError: invalid syntax`

It seems there's a small error in the __init__ file. Would you guys be able to fix that?

UPDATE: I fixed it locally by editing the __init__ file. I changed `except ArpackNoConvergence, e` to `except ArpackNoConvergence as e`

Another UPDATE: I see that you actually made this change correctly on Github. However, this change doesn't show up when pulling the package from PyPI. You probably just need to upload a new version of the package there.

**Comment by brandones** [comment]
Oh yeah, I need to do a release! Thanks @nickchak21 , I'll do that. Sorry for the trouble.

**Comment by brandones** [comment]
0.6 is out! https://pypi.org/project/graphpca/
